### ISSUE TITLE
login credentials?

### ISSUE THREAD

**Issue by gk7279** [mickael-kerjean/webpty#1]
The webpage is asking for username/password.

When the authorized users' credentials on the box were given, it doesn't take it.

Any idea why?

**Comment by mickael-kerjean** [comment]
At the moment users are authenticated via ssh. If that doesn't work for you:
1. do you have openssh installed?
2. if so, do you use something else than port 22?

**Comment by NightMachinery** [comment]
@mickael-kerjean Can you elaborate? How does it use SSH to authorize users? Should the user upload their private/public keys to the website?

Is SSH only used for authorization?

**Comment by mickael-kerjean** [comment]
It means in the current model, you will be able to plug and play various authentication mechanism. The one currently implemented is based of SSH in that a shell is opened only if you have SSH access to the machine. If I can put some more time to this, you will be able to plug other authentication mechanism like an htpasswd file, LDAP, SAML or whatnot.

As for authorisation, the shell is opened from whatever user you are running webpty from
