### ISSUE TITLE
Can I use the configuration file to change the listening port and SSH connection information

### ISSUE THREAD

**Issue by flytkgl** [mickael-kerjean/webpty#2]
Can I use the configuration file to change the listening port and SSH connection information

**Comment by mickael-kerjean** [comment]
Yes that should definitely be a feature, do you think you can make a PR for this?

**Comment by mickael-kerjean** [comment]
done in bb563533bb9553f01b97ffc7a3cde67931f008b6 :smile:

**Comment by flytkgl** [comment]
> done in [bb56353](https://github.com/mickael-kerjean/webpty/commit/bb563533bb9553f01b97ffc7a3cde67931f008b6) 😄

so good
